# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70241e824ced97b16a7e5d2d7ea48fe764ff09e5731d649007fdd5253004126fec4cb88baf4cf6f8db440f1d14ae3c95a804eace6c4da5e35587e473145fc424

test:
  secret_key_base: 2c17d3d20ed0e2507f1ec34b42566eee3779d683e708bbed359915a9cc2c3035c8508e598378365fa6de2abc700627f5044f4fc8981f416fc313a316e6aa7753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
